// <auto-generated />
using System;
using Logaffe.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LogaffeDbContext))]
    [Migration("20260823075942_AlertNotifier")]
    partial class AlertNotifier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gin");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logaffe.Domain.Alerts.ConditionState", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<short>("Condition")
                        .HasColumnType("smallint")
                        .HasColumnName("condition");

                    b.Property<int>("Latched")
                        .HasColumnType("integer")
                        .HasColumnName("latched");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_at");

                    b.Property<int>("NotifiedLevel")
                        .HasColumnType("integer")
                        .HasColumnName("notified_level");

                    b.HasKey("SubjectId", "Condition")
                        .HasName("pk_alert_condition_state");

                    b.ToTable("alert_condition_state", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Entries.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<bool>("ExceptionTruncated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exception_truncated");

                    b.Property<string>("Instance")
                        .HasColumnType("text")
                        .HasColumnName("instance");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("LoggerName")
                        .HasColumnType("text")
                        .HasColumnName("logger_name");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<bool>("MessageTruncated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("message_truncated");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTimeOffset>("ReceiptTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receipt_time");

                    b.Property<string>("RenderedMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rendered_message");

                    b.Property<byte[]>("SpanId")
                        .HasColumnType("bytea")
                        .HasColumnName("span_id");

                    b.Property<byte[]>("TraceId")
                        .HasColumnType("bytea")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_entry");

                    b.HasIndex(new[] { "ProjectId", "Instance", "EventTime" }, "ix_log_entry_instance")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "ProjectId", "LoggerName", "EventTime" }, "ix_log_entry_logger_name")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "ProjectId", "EventTime", "Id" }, "ix_log_entry_paging")
                        .IsDescending(false, true, true);

                    b.HasIndex(new[] { "ProjectId", "ReceiptTime", "Id" }, "ix_log_entry_receipt");

                    b.HasIndex(new[] { "ProjectId", "RenderedMessage" }, "ix_log_entry_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "ProjectId", "RenderedMessage" }, "ix_log_entry_search"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "ProjectId", "RenderedMessage" }, "ix_log_entry_search"), new[] { "", "gin_trgm_ops" });

                    b.HasIndex(new[] { "ProjectId", "TraceId", "EventTime" }, "ix_log_entry_trace")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "ProjectId", "EventTime", "Id" }, "ix_log_entry_warning_and_above")
                        .IsDescending(false, true, true)
                        .HasFilter("level >= 3");

                    b.ToTable("log_entry", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.FilesystemReading", b =>
                {
                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset>("ReceiptTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receipt_time");

                    b.Property<string>("MountPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mount_path");

                    b.Property<long>("Total")
                        .HasColumnType("bigint")
                        .HasColumnName("total");

                    b.Property<long>("Used")
                        .HasColumnType("bigint")
                        .HasColumnName("used");

                    b.HasKey("HostId", "ReceiptTime", "MountPath")
                        .HasName("pk_filesystem_reading");

                    b.ToTable("filesystem_reading", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_host");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_host_name");

                    b.ToTable("host", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.Sample", b =>
                {
                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset>("ReceiptTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receipt_time");

                    b.Property<float>("Cpu")
                        .HasColumnType("real")
                        .HasColumnName("cpu");

                    b.Property<float>("Load1")
                        .HasColumnType("real")
                        .HasColumnName("load_1");

                    b.Property<float>("Load15")
                        .HasColumnType("real")
                        .HasColumnName("load_15");

                    b.Property<float>("Load5")
                        .HasColumnType("real")
                        .HasColumnName("load_5");

                    b.Property<long>("MemoryTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_total");

                    b.Property<long>("MemoryUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_used");

                    b.HasKey("HostId", "ReceiptTime")
                        .HasName("pk_host_sample");

                    b.ToTable("host_sample", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Operators.BackupCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_backup_code");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_backup_code_hash");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_backup_code_operator");

                    b.ToTable("backup_code", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Operators.ClaimGuard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("DrawnSecretHash")
                        .HasColumnType("bytea")
                        .HasColumnName("drawn_secret_hash");

                    b.Property<bool>("OnlyGuard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("only_guard");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.HasKey("Id")
                        .HasName("pk_claim_guard");

                    b.HasIndex("OnlyGuard")
                        .IsUnique()
                        .HasDatabaseName("ix_claim_guard_only_one");

                    b.ToTable("claim_guard", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Operators.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<byte[]>("EncryptedSecondFactorSecret")
                        .HasColumnType("bytea")
                        .HasColumnName("second_factor_secret");

                    b.Property<bool>("OnlyOperator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("only_operator");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("SecondFactorEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("second_factor_enrolled_at");

                    b.HasKey("Id")
                        .HasName("pk_operator");

                    b.HasIndex("OnlyOperator")
                        .IsUnique()
                        .HasDatabaseName("ix_operator_only_one");

                    b.ToTable("operator", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Operators.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastSeenFrom")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_seen_from");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_session_operator");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ix_session_secret");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_project_group");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_project_group_name");

                    b.ToTable("project_group", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("Muted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("muted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Retention")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_project_host");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_project_group_id_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("GroupId", "Name"), false);

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.Tally", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("Hour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour");

                    b.Property<long>("AtErrorOrAbove")
                        .HasColumnType("bigint")
                        .HasColumnName("at_error_or_above");

                    b.Property<long>("Entries")
                        .HasColumnType("bigint")
                        .HasColumnName("entries");

                    b.HasKey("ProjectId", "Hour")
                        .HasName("pk_project_tally");

                    b.ToTable("project_tally", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.AgentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<bool>("MayDestroy")
                        .HasColumnType("boolean")
                        .HasColumnName("may_destroy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_agent_token");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_token_identifier");

                    b.ToTable("agent_token", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.HostToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.HasKey("Id")
                        .HasName("pk_host_token");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_host_token_host");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_host_token_identifier");

                    b.ToTable("host_token", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.IngestToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_ingest_token");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_ingest_token_identifier");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_ingest_token_project");

                    b.ToTable("ingest_token", (string)null);
                });

            modelBuilder.Entity("Logaffe.Infrastructure.Persistence.InstallationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AlertOnFillingUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alert_on_filling_up");

                    b.Property<bool>("AlertOnFlooding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alert_on_flooding");

                    b.Property<bool>("AlertOnGoneQuiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alert_on_gone_quiet");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("MountPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mount_path");

                    b.Property<byte[]>("NotifierAccessToken")
                        .HasColumnType("bytea")
                        .HasColumnName("notifier_access_token");

                    b.Property<string>("NotifierServer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("notifier_server");

                    b.Property<string>("NotifierTopic")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("notifier_topic");

                    b.Property<bool>("OnlySettings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("only_settings");

                    b.Property<int>("SampleRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("sample_retention_days");

                    b.HasKey("Id")
                        .HasName("pk_installation_settings");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_installation_settings_host");

                    b.HasIndex("OnlySettings")
                        .IsUnique()
                        .HasDatabaseName("ix_installation_settings_only_one");

                    b.ToTable("installation_settings", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.FilesystemReading", b =>
                {
                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_filesystem_reading_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.Sample", b =>
                {
                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_host_sample_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Operators.BackupCode", b =>
                {
                    b.HasOne("Logaffe.Domain.Operators.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backup_code_operator");
                });

            modelBuilder.Entity("Logaffe.Domain.Operators.Session", b =>
                {
                    b.HasOne("Logaffe.Domain.Operators.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_operator");
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.Project", b =>
                {
                    b.HasOne("Logaffe.Domain.Projects.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_project_group");

                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.HostToken", b =>
                {
                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_host_token_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.IngestToken", b =>
                {
                    b.HasOne("Logaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingest_token_project");
                });

            modelBuilder.Entity("Logaffe.Infrastructure.Persistence.InstallationSettings", b =>
                {
                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_installation_settings_host");
                });
#pragma warning restore 612, 618
        }
    }
}
