// <auto-generated />
using System;
using Logaffe.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LogaffeDbContext))]
    [Migration("20260807073701_IngestAndAgentTokens")]
    partial class IngestAndAgentTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logaffe.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Retention")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_project_name");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.AgentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_agent_token");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_token_identifier");

                    b.ToTable("agent_token", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.IngestToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_ingest_token");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_ingest_token_identifier");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_ingest_token_project");

                    b.ToTable("ingest_token", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.IngestToken", b =>
                {
                    b.HasOne("Logaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingest_token_project");
                });
#pragma warning restore 612, 618
        }
    }
}
