// <auto-generated />
using System;
using Logaffe.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LogaffeDbContext))]
    [Migration("20260906124825_TheHistory")]
    partial class TheHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gin");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logaffe.Domain.Alerts.ConditionState", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<short>("Condition")
                        .HasColumnType("smallint")
                        .HasColumnName("condition");

                    b.Property<int>("Latched")
                        .HasColumnType("integer")
                        .HasColumnName("latched");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_at");

                    b.Property<int>("NotifiedLevel")
                        .HasColumnType("integer")
                        .HasColumnName("notified_level");

                    b.HasKey("SubjectId", "Condition")
                        .HasName("pk_alert_condition_state");

                    b.ToTable("alert_condition_state", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Entries.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<bool>("ExceptionTruncated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exception_truncated");

                    b.Property<string>("Instance")
                        .HasColumnType("text")
                        .HasColumnName("instance");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("LoggerName")
                        .HasColumnType("text")
                        .HasColumnName("logger_name");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<bool>("MessageTruncated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("message_truncated");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTimeOffset>("ReceiptTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receipt_time");

                    b.Property<string>("RenderedMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rendered_message");

                    b.Property<byte[]>("SpanId")
                        .HasColumnType("bytea")
                        .HasColumnName("span_id");

                    b.Property<byte[]>("TraceId")
                        .HasColumnType("bytea")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_entry");

                    b.HasIndex(new[] { "ProjectId", "Instance", "EventTime" }, "ix_log_entry_instance")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "ProjectId", "LoggerName", "EventTime" }, "ix_log_entry_logger_name")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "ProjectId", "EventTime", "Id" }, "ix_log_entry_paging")
                        .IsDescending(false, true, true);

                    b.HasIndex(new[] { "ProjectId", "ReceiptTime", "Id" }, "ix_log_entry_receipt");

                    b.HasIndex(new[] { "ProjectId", "RenderedMessage" }, "ix_log_entry_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "ProjectId", "RenderedMessage" }, "ix_log_entry_search"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "ProjectId", "RenderedMessage" }, "ix_log_entry_search"), new[] { "", "gin_trgm_ops" });

                    b.HasIndex(new[] { "ProjectId", "TraceId", "EventTime" }, "ix_log_entry_trace")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "ProjectId", "EventTime", "Id" }, "ix_log_entry_warning_and_above")
                        .IsDescending(false, true, true)
                        .HasFilter("level >= 3");

                    b.ToTable("log_entry", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.History.Change", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Act")
                        .HasColumnType("integer")
                        .HasColumnName("act");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<int>("ActorKind")
                        .HasColumnType("integer")
                        .HasColumnName("actor_kind");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_name");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Field")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field");

                    b.Property<string>("From")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("moved_from");

                    b.Property<int>("Subject")
                        .HasColumnType("integer")
                        .HasColumnName("subject");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_name");

                    b.Property<string>("To")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("moved_to");

                    b.HasKey("Id")
                        .HasName("pk_change");

                    b.HasIndex("ActorId");

                    b.HasIndex("Subject", "SubjectId")
                        .HasDatabaseName("ix_change_subject");

                    b.ToTable("change", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.FilesystemReading", b =>
                {
                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset>("ReceiptTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receipt_time");

                    b.Property<string>("MountPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mount_path");

                    b.Property<long>("Total")
                        .HasColumnType("bigint")
                        .HasColumnName("total");

                    b.Property<long>("Used")
                        .HasColumnType("bigint")
                        .HasColumnName("used");

                    b.HasKey("HostId", "ReceiptTime", "MountPath")
                        .HasName("pk_filesystem_reading");

                    b.ToTable("filesystem_reading", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_host");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_host_name");

                    b.ToTable("host", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.Sample", b =>
                {
                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset>("ReceiptTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receipt_time");

                    b.Property<float>("Cpu")
                        .HasColumnType("real")
                        .HasColumnName("cpu");

                    b.Property<float>("Load1")
                        .HasColumnType("real")
                        .HasColumnName("load_1");

                    b.Property<float>("Load15")
                        .HasColumnType("real")
                        .HasColumnName("load_15");

                    b.Property<float>("Load5")
                        .HasColumnType("real")
                        .HasColumnName("load_5");

                    b.Property<long>("MemoryTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_total");

                    b.Property<long>("MemoryUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_used");

                    b.HasKey("HostId", "ReceiptTime")
                        .HasName("pk_host_sample");

                    b.ToTable("host_sample", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.BackupCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_backup_code");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_backup_code_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_backup_code_user");

                    b.ToTable("backup_code", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Administrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("administrator");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("kind")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_identity");

                    b.ToTable("identity", null, t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", " \"kind\" in (0, 1) ");

                            t.HasCheckConstraint("ck_identity_owner", "\"kind\" = 0 and \"owner_id\" is null\nor \"kind\" = 1 and \"owner_id\" is not null and not \"administrator\"");

                            t.HasCheckConstraint("ck_identity_user", "\"kind\" = 0\n    and \"email\" is not null and \"normalized_email\" is not null\n    and \"state\" in (0, 1, 2)\nor \"kind\" = 1\n    and \"email\" is null and \"normalized_email\" is null\n    and \"state\" is null and \"password_hash\" is null\n    and \"second_factor_secret\" is null");
                        });

                    b.HasDiscriminator<int>("kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.OneTimeSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("pending_email");

                    b.Property<string>("PendingNormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("pending_normalized_email");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_one_time_secret");

                    b.HasIndex("PendingNormalizedEmail")
                        .HasDatabaseName("ix_one_time_secret_pending")
                        .HasFilter("\"used_at\" is null and \"pending_normalized_email\" is not null");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ix_one_time_secret_hash");

                    b.HasIndex("UserId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ix_one_time_secret_live")
                        .HasFilter("\"used_at\" is null");

                    b.ToTable("one_time_secret", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastSeenFrom")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_seen_from");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ix_session_secret");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_user");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_project_group");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_project_group_name");

                    b.ToTable("project_group", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("Muted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("muted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Retention")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_project_host");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_project_group_id_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("GroupId", "Name"), false);

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.ProjectAccess", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_access");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_access_user");

                    b.ToTable("project_access", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.Tally", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("Hour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour");

                    b.Property<long>("AtErrorOrAbove")
                        .HasColumnType("bigint")
                        .HasColumnName("at_error_or_above");

                    b.Property<long>("Entries")
                        .HasColumnType("bigint")
                        .HasColumnName("entries");

                    b.HasKey("ProjectId", "Hour")
                        .HasName("pk_project_tally");

                    b.ToTable("project_tally", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.AgentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("identifier");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<bool>("MayDestroy")
                        .HasColumnType("boolean")
                        .HasColumnName("may_destroy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_agent_token");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_token_identifier");

                    b.HasIndex("IdentityId")
                        .HasDatabaseName("ix_agent_token_identity");

                    b.ToTable("agent_token", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.HostToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.HasKey("Id")
                        .HasName("pk_host_token");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_host_token_host");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_host_token_identifier");

                    b.ToTable("host_token", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.IngestToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_ingest_token");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_ingest_token_identifier");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_ingest_token_project");

                    b.ToTable("ingest_token", (string)null);
                });

            modelBuilder.Entity("Logaffe.Infrastructure.Persistence.InstallationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AlertOnFailing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alert_on_failing");

                    b.Property<bool>("AlertOnFillingUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alert_on_filling_up");

                    b.Property<bool>("AlertOnFlooding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alert_on_flooding");

                    b.Property<bool>("AlertOnGoneQuiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alert_on_gone_quiet");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("MountPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mount_path");

                    b.Property<byte[]>("NotifierAccessToken")
                        .HasColumnType("bytea")
                        .HasColumnName("notifier_access_token");

                    b.Property<string>("NotifierServer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("notifier_server");

                    b.Property<string>("NotifierTopic")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("notifier_topic");

                    b.Property<bool>("OnlySettings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("only_settings");

                    b.Property<int>("SampleRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("sample_retention_days");

                    b.HasKey("Id")
                        .HasName("pk_installation_settings");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_installation_settings_host");

                    b.HasIndex("OnlySettings")
                        .IsUnique()
                        .HasDatabaseName("ix_installation_settings_only_one");

                    b.ToTable("installation_settings", (string)null);
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.Agent", b =>
                {
                    b.HasBaseType("Logaffe.Domain.Identities.Identity");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_identity_owner");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", " \"kind\" in (0, 1) ");

                            t.HasCheckConstraint("ck_identity_owner", "\"kind\" = 0 and \"owner_id\" is null\nor \"kind\" = 1 and \"owner_id\" is not null and not \"administrator\"");

                            t.HasCheckConstraint("ck_identity_user", "\"kind\" = 0\n    and \"email\" is not null and \"normalized_email\" is not null\n    and \"state\" in (0, 1, 2)\nor \"kind\" = 1\n    and \"email\" is null and \"normalized_email\" is null\n    and \"state\" is null and \"password_hash\" is null\n    and \"second_factor_secret\" is null");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.User", b =>
                {
                    b.HasBaseType("Logaffe.Domain.Identities.Identity");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<byte[]>("EncryptedSecondFactorSecret")
                        .HasColumnType("bytea")
                        .HasColumnName("second_factor_secret");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("SecondFactorEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("second_factor_enrolled_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_normalized_email");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", " \"kind\" in (0, 1) ");

                            t.HasCheckConstraint("ck_identity_owner", "\"kind\" = 0 and \"owner_id\" is null\nor \"kind\" = 1 and \"owner_id\" is not null and not \"administrator\"");

                            t.HasCheckConstraint("ck_identity_user", "\"kind\" = 0\n    and \"email\" is not null and \"normalized_email\" is not null\n    and \"state\" in (0, 1, 2)\nor \"kind\" = 1\n    and \"email\" is null and \"normalized_email\" is null\n    and \"state\" is null and \"password_hash\" is null\n    and \"second_factor_secret\" is null");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Logaffe.Domain.History.Change", b =>
                {
                    b.HasOne("Logaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_change_actor");
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.FilesystemReading", b =>
                {
                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_filesystem_reading_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Hosts.Sample", b =>
                {
                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_host_sample_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.BackupCode", b =>
                {
                    b.HasOne("Logaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backup_code_user");
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.OneTimeSecret", b =>
                {
                    b.HasOne("Logaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_one_time_secret_user");
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.Session", b =>
                {
                    b.HasOne("Logaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_user");
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.Project", b =>
                {
                    b.HasOne("Logaffe.Domain.Projects.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_project_group");

                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Projects.ProjectAccess", b =>
                {
                    b.HasOne("Logaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_access_project");

                    b.HasOne("Logaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_access_user");
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.AgentToken", b =>
                {
                    b.HasOne("Logaffe.Domain.Identities.Agent", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_token_identity");
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.HostToken", b =>
                {
                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_host_token_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Tokens.IngestToken", b =>
                {
                    b.HasOne("Logaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingest_token_project");
                });

            modelBuilder.Entity("Logaffe.Infrastructure.Persistence.InstallationSettings", b =>
                {
                    b.HasOne("Logaffe.Domain.Hosts.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_installation_settings_host");
                });

            modelBuilder.Entity("Logaffe.Domain.Identities.Agent", b =>
                {
                    b.HasOne("Logaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_owner");
                });
#pragma warning restore 612, 618
        }
    }
}
